In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr[4])

5


#### Accessing 2-D arrays

In [8]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[0][0])
print(arr1[1][2])
print(arr1[1,4])


1
8
10


#### Accessing 3-D array

In [13]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2)
print(arr2[0,1,2])
print(arr2[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
12


#### Negative Indexing


In [21]:
#print last element of 2nd Dimention
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3[0,-3])

2
