# Array Slicing
Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [1]:
import numpy as np


In [5]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6]
[1 2 3 4]


# Negative Slicing
Use the minus operator to refer to an index from the end:

In [14]:
arr3 = np.array([1,2,3,4,5,6,7,8,9])
print(arr3[-3:-1])
print(arr3[:-1])
print(arr3[-2:-1])

[7 8]
[1 2 3 4 5 6 7 8]
[8]


In [16]:
print(arr3[::2])

[1 3 5 7 9]


### Slicing 2-D Array

In [22]:
arr4 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr4[1, 1:4])
print(arr4[0:2,2])

[ 8  9 10]
[3 9]


In [23]:
print(arr4[0:2,1:4])

[[ 2  3  4]
 [ 8  9 10]]
