The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [1]:
#Copy

import numpy as np 


In [6]:
arr = np.array([1,2,3,4,5])
newarr = arr.copy()
print('---original array----')
print(arr)
print(newarr)

arr[0] = 42
newarr[1] = 32
print('---after changes in original and copy array-----')
print(arr)
print(newarr)

---original array----
[1 2 3 4 5]
[1 2 3 4 5]
---after changes in original and copy array-----
[42  2  3  4  5]
[ 1 32  3  4  5]


In [7]:
#view
arr1 = np.array([1,2,3,4,5])
newarr1 = arr1.view()
print('---original array----')
print(arr1)
print(newarr1)

arr1[0] = 42
newarr1[1] = 32
print('---after changes in original and copy array-----')
print(arr1)
print(newarr1)

---original array----
[1 2 3 4 5]
[1 2 3 4 5]
---after changes in original and copy array-----
[42 32  3  4  5]
[42 32  3  4  5]


In [8]:
#Check array owns the data or not
# As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.
arr2= np.array([1,2,5,8,7])
x = arr2.copy()
y= arr2.view()

print(x.base)
print(y.base)

None
[1 2 5 8 7]
