### Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [1]:
import numpy as np


In [7]:
arr = np.array([[1,5,3,4],[5,6,7,8],[2,3,6,8]])
print(arr.shape)
print(arr)

(3, 4)
[[1 5 3 4]
 [5 6 7 8]
 [2 3 6 8]]


In [9]:
arr1 = np.array([1,2,3,5,5],ndmin=5)
print(arr1)
print(arr1.shape)

[[[[[1 2 3 5 5]]]]]
(1, 1, 1, 1, 5)


### Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [15]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr2.shape)
newarr = arr2.reshape(4,3)
print(newarr)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
#Reshape 1-D to 3-D array

arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr3.shape)
print('the outermost dimesion will have 2 arrays that contains 3 arrays with 2 elements')
newarr1 = arr3.reshape(2,3,2)
print(newarr1)

print('the outermost dimesion will have 2 arrays that contains 2 arrays with 3 elements')
newarr1 = arr3.reshape(2,2,3)
print(newarr1)


(12,)
the outermost dimesion will have 2 arrays that contains 3 arrays with 2 elements
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
the outermost dimesion will have 2 arrays that contains 2 arrays with 3 elements
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [35]:
arr3 = np.array([1,2,3,4,5,6,7,8])
newarr3 = arr3.reshape(2,4)
print(newarr3.ndim)
print(newarr3)
print(newarr3.base)

2
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [43]:
arr4 = np.array([1,2,3,4,5,6,7,8])
newarr4 = arr4.reshape(2,2,-1)
print(newarr4)
print(newarr4.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [45]:
arr5 = np.array([[1,2,3],[4,5,6]])
newarr5  = arr5.reshape(-1)
print(newarr5)
print(newarr5.base)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
