In [2]:
#Create a 0-D array with value 42
import numpy as np

In [5]:
arr = np.array(42)
print(arr)

42


In [7]:
#Create a 1-D array containing the values 1,2,3,4,5:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [10]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [11]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
